### ISSUE TITLE
Random Puzzle links not redirecting to puzzle page

### ISSUE THREAD

**Issue by jalpp** [sornerol/chess-com-pubapi-java-wrapper#6] opened 2022-06-29 18:53 UTC
# Describe the bug
the puzzle links redirect to https://www.chess.com/daily-chess-puzzle rather than links to specific puzzle link
# Wrapper version
Which version of the API wrapper are you using? (e.g. 1.0.0)
1.0.0
# Java version
Which version of Java are you using? (e.g. 1.8)
17
# Steps to reproduce the behavior:
List the steps needed to reproduce the behavior.
this.dailyPuzzleClient = new DailyPuzzleClient();
this.dailyPuzzleClient.getRandomDailyPuzzle().getUrl();
# Expected behavior
should return specific puzzle cc puzzle link.
# Additional context

**Comment by sornerol** [comment] 2022-06-29 23:20
The problem is that the URLs being returned by chess.com are redirecting to their main Daily Chess Puzzles page. I have provided a bug report to Chess.com.

Closing this issue since it is a bug with Chess.com's API rather than with this API wrapper.

**Closed by sornerol** 2022-06-29 23:20 UTC
Labels: bug
